name: Сообщить о проблеме
description: Опишите ошибку или трудность.
title: "[Проблема]: "
labels: ["bug"]
body:
  - type: input
    id: app_version
    attributes:
      label: Версия приложения
      placeholder: v1.2.3
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: Описание проблемы
      placeholder: Что произошло? Шаги для воспроизведения...
    validations:
      required: true
